% Nick McCullough, Brendan MacLaren, Ryan McLenithan, Lab 5

kit(2) = struct('sub', ... 
      struct('id',123,'wt',4.4,'code','a'),... 
      'name', 'xyz', 'lens', [4 7]) 
kit(1) = struct('sub', ... 
      struct('id',33,'wt',11.11,'code','q'), ... 
      'name', 'rst', 'lens', 5:6) 

kit(1).code 