clear,clc
% Nick McCullough, AerE 161, HW 6, Problem 12.13
% create a file to store blade diameter, wind velocity, and electricity
% generated and then display the data in a graph (3D Graph)

% the graph will need a title and three value titles, x y z
% all data is saved in windturbine.dat

% let's load the data
load windturbine.dat
% now let's write the plot code, we will use stem3 for x y z 3D graphing
stem3(windturbine(:,1),windturbine(:,2),windturbine(:,3))
% this reads and plots the data. it was stored in three different columns

% now let's create the x y and z labels for our data
xlabel('Blade Diameter of Wind Turbine in ft')
ylabel('Velocity of Wind in mph')
zlabel('Approximate Electricity Generated by Turbine in kW per hr/year')
title('Wind Turbine Data ') % title of graph